"""initial control chain schema

Revision ID: 8b19fad92700
Revises: 
Create Date: 2026-08-07 16:56:07.224541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b19fad92700'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('order_ref', sa.String(), nullable=False),
    sa.Column('seller_ref', sa.String(), nullable=False),
    sa.Column('product_ref', sa.String(), nullable=False),
    sa.Column('risk_band', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('source_refs', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('state_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_index(op.f('ix_cases_order_ref'), 'cases', ['order_ref'], unique=False)
    op.create_index(op.f('ix_cases_product_ref'), 'cases', ['product_ref'], unique=False)
    op.create_index(op.f('ix_cases_seller_ref'), 'cases', ['seller_ref'], unique=False)
    op.create_table('source_snapshots',
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('source_class', sa.String(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('allowed_for_evidence', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('source_id'),
    sa.UniqueConstraint('source_id', 'version', name='uq_source_version')
    )
    op.create_index(op.f('ix_source_snapshots_source_class'), 'source_snapshots', ['source_class'], unique=False)
    op.create_table('authority_records',
    sa.Column('authority_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('proposed_action', sa.String(), nullable=False),
    sa.Column('decision', sa.Enum('ALLOW', 'DENY', 'REQUIRE_HUMAN', name='authoritydecision'), nullable=False),
    sa.Column('reason_codes', sa.JSON(), nullable=False),
    sa.Column('required_role', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('policy_version', sa.String(), nullable=False),
    sa.Column('input_hash', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('authority_id')
    )
    op.create_index(op.f('ix_authority_records_case_id'), 'authority_records', ['case_id'], unique=False)
    op.create_table('claims',
    sa.Column('claim_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('claim_type', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('TRUE', 'FALSE', 'UNKNOWN', name='claimstatus'), nullable=False),
    sa.Column('evidence_ids', sa.JSON(), nullable=False),
    sa.Column('counter_evidence_ids', sa.JSON(), nullable=False),
    sa.Column('rule_version', sa.String(), nullable=False),
    sa.Column('reason_codes', sa.JSON(), nullable=False),
    sa.Column('confidence_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('claim_id'),
    sa.UniqueConstraint('case_id', 'claim_type', name='uq_case_claim_type')
    )
    op.create_index(op.f('ix_claims_case_id'), 'claims', ['case_id'], unique=False)
    op.create_table('evidence',
    sa.Column('evidence_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('source_version', sa.String(), nullable=True),
    sa.Column('locator', sa.String(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('excerpt_kind', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('authority_status', sa.String(), nullable=False),
    sa.Column('entity_binding_status', sa.String(), nullable=False),
    sa.Column('support_status', sa.String(), nullable=False),
    sa.Column('validation_reasons', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['source_snapshots.source_id'], ),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    op.create_index(op.f('ix_evidence_case_id'), 'evidence', ['case_id'], unique=False)
    op.create_index('ix_evidence_case_source', 'evidence', ['case_id', 'source_id'], unique=False)
    op.create_table('outcomes',
    sa.Column('outcome_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('attempt_id', sa.String(), nullable=False),
    sa.Column('intended_action', sa.String(), nullable=False),
    sa.Column('observed_result', sa.String(), nullable=False),
    sa.Column('reconciliation_status', sa.String(), nullable=False),
    sa.Column('mismatch_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('outcome_id'),
    sa.UniqueConstraint('case_id', 'attempt_id', name='uq_case_attempt')
    )
    op.create_index(op.f('ix_outcomes_case_id'), 'outcomes', ['case_id'], unique=False)
    op.create_table('review_tasks',
    sa.Column('review_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reason_codes', sa.JSON(), nullable=False),
    sa.Column('assigned_role', sa.String(), nullable=False),
    sa.Column('reviewer_id', sa.String(), nullable=True),
    sa.Column('reviewer_decision', sa.String(), nullable=True),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_index(op.f('ix_review_tasks_case_id'), 'review_tasks', ['case_id'], unique=False)
    op.create_table('trace_events',
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('tool_name', sa.String(), nullable=True),
    sa.Column('argument_hash', sa.String(), nullable=True),
    sa.Column('result_hash', sa.String(), nullable=True),
    sa.Column('state_before_hash', sa.String(), nullable=True),
    sa.Column('state_after_hash', sa.String(), nullable=True),
    sa.Column('evidence_ids', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trace_id'),
    sa.UniqueConstraint('case_id', 'sequence', name='uq_case_sequence')
    )
    op.create_index(op.f('ix_trace_events_case_id'), 'trace_events', ['case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trace_events_case_id'), table_name='trace_events')
    op.drop_table('trace_events')
    op.drop_index(op.f('ix_review_tasks_case_id'), table_name='review_tasks')
    op.drop_table('review_tasks')
    op.drop_index(op.f('ix_outcomes_case_id'), table_name='outcomes')
    op.drop_table('outcomes')
    op.drop_index('ix_evidence_case_source', table_name='evidence')
    op.drop_index(op.f('ix_evidence_case_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_claims_case_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_authority_records_case_id'), table_name='authority_records')
    op.drop_table('authority_records')
    op.drop_index(op.f('ix_source_snapshots_source_class'), table_name='source_snapshots')
    op.drop_table('source_snapshots')
    op.drop_index(op.f('ix_cases_seller_ref'), table_name='cases')
    op.drop_index(op.f('ix_cases_product_ref'), table_name='cases')
    op.drop_index(op.f('ix_cases_order_ref'), table_name='cases')
    op.drop_table('cases')
    # ### end Alembic commands ###
