"""agent orchestration schema

Revision ID: d90769dacba0
Revises: 66288f83c2a0
Create Date: 2026-08-24 20:43:18.673801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd90769dacba0'
down_revision: Union[str, Sequence[str], None] = '66288f83c2a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_definitions',
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('config_hash', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('agent_id')
    )
    op.create_table('agent_runs',
    sa.Column('agent_run_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('parent_run_id', sa.String(), nullable=True),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('max_tool_calls', sa.Integer(), nullable=False),
    sa.Column('max_steps', sa.Integer(), nullable=False),
    sa.Column('max_wall_clock_seconds', sa.Float(), nullable=True),
    sa.Column('tool_calls_used', sa.Integer(), nullable=False),
    sa.Column('steps_used', sa.Integer(), nullable=False),
    sa.Column('termination_status', sa.String(), nullable=True),
    sa.Column('termination_reason_codes', sa.JSON(), nullable=False),
    sa.Column('token_usage_prompt', sa.Integer(), nullable=True),
    sa.Column('token_usage_completion', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("stage = 'INVESTIGATE'", name='ck_agent_run_stage_investigate_only'),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_definitions.agent_id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_run_id'], ['agent_runs.agent_run_id'], ),
    sa.PrimaryKeyConstraint('agent_run_id')
    )
    op.create_index(op.f('ix_agent_runs_agent_id'), 'agent_runs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_case_id'), 'agent_runs', ['case_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_parent_run_id'), 'agent_runs', ['parent_run_id'], unique=False)
    op.create_table('agent_handoffs',
    sa.Column('handoff_id', sa.String(), nullable=False),
    sa.Column('parent_run_id', sa.String(), nullable=False),
    sa.Column('child_run_id', sa.String(), nullable=False),
    sa.Column('from_agent_id', sa.String(), nullable=False),
    sa.Column('to_agent_id', sa.String(), nullable=False),
    sa.Column('delegated_task', sa.String(), nullable=False),
    sa.Column('reason_codes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['child_run_id'], ['agent_runs.agent_run_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_agent_id'], ['agent_definitions.agent_id'], ),
    sa.ForeignKeyConstraint(['parent_run_id'], ['agent_runs.agent_run_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_agent_id'], ['agent_definitions.agent_id'], ),
    sa.PrimaryKeyConstraint('handoff_id'),
    sa.UniqueConstraint('child_run_id')
    )
    op.create_index(op.f('ix_agent_handoffs_parent_run_id'), 'agent_handoffs', ['parent_run_id'], unique=False)
    op.create_table('agent_steps',
    sa.Column('step_id', sa.String(), nullable=False),
    sa.Column('agent_run_id', sa.String(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.String(), nullable=False),
    sa.Column('tool_name', sa.String(), nullable=True),
    sa.Column('tool_input_hash', sa.String(), nullable=True),
    sa.Column('tool_output_hash', sa.String(), nullable=True),
    sa.Column('candidate_evidence_ids', sa.JSON(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.agent_run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('step_id'),
    sa.UniqueConstraint('agent_run_id', 'sequence', name='uq_agent_run_sequence')
    )
    op.create_index(op.f('ix_agent_steps_agent_run_id'), 'agent_steps', ['agent_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_steps_agent_run_id'), table_name='agent_steps')
    op.drop_table('agent_steps')
    op.drop_index(op.f('ix_agent_handoffs_parent_run_id'), table_name='agent_handoffs')
    op.drop_table('agent_handoffs')
    op.drop_index(op.f('ix_agent_runs_parent_run_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_case_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_agent_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_table('agent_definitions')
    # ### end Alembic commands ###
